from django.urls import path

from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('services/', CreateService.as_view(), name='services'),
    path('delete_service', delete_service, name='delete_service'),
    path('delete_unit', delete_unit, name='delete_unit'),
    path('tariff_list/', TariffList.as_view(), name='tariff_list'),
    path('create_tariff/', CreateTariff.as_view(), name='create_tariff'),
    path('update_tariff/<int:pk>', UpdateTariff.as_view(), name='update_tariff'),
    path('tariff/<int:pk>', ShowTariff.as_view(), name='tariff'),
    path('get_unit_by_service', get_unit_by_service, name='get_unit_by_service'),
    path('tariff_list/delete_tariff/<int:tariff_id>', delete_tariff, name='delete_tariff'),
    path('delete_service_tariff', delete_service_tariff, name='delete_service_tariff'),
    path('roles/', RoleList.as_view(), name='roles'),
    path('user_list/', UserList.as_view(), name='user_list'),
    path('create_user/', CreateUser.as_view(), name='create_user'),
    path('update_user/<int:pk>', UpdateUser.as_view(), name='update_user'),
    path('user_list/delete_user/<int:user_id>', delete_user, name='delete_user'),
    path('show_profile/<int:pk>', ShowProfile.as_view(), name='show_profile'),
    path('payment_details/', PaymentDetailsView.as_view(), name='payment_details'),
    path('payment_items/', PaymentItemList.as_view(), name='payment_items'),
    path('create_payment/', PaymentItemCreate.as_view(), name='create_payment'),
    path('update_payment/<int:pk>', PaymentItemUpdate.as_view(), name='update_payment'),
    path('payment_items/delete_payment/<int:payment_id>', delete_payment, name='delete_payment'),
    path('main_page/', MainPageView.as_view(), name='main_pagev'),
    path('info_page/', InfoPage.as_view(), name='info_pagev'),
    path('service_page/', ServicePageView.as_view(), name='service_pagev'),
    path('contact_page/', ContactPageView.as_view(), name='contact_pagev'),
    path('delete_document/<int:pk>', delete_document, name='delete_document'),
    path('delete_image_gallery/<int:image_id>', delete_from_gallery, name='delete_image'),
    path('delete_service_page/<int:service_id>', delete_service_page, name='delete_service_page'),
    path('clone_tariff/<int:pk>', CloneTariff.as_view(), name='clone_tariff'),
    path('owner_list/', OwnerList.as_view(), name='owner_list'),
    path('create_owner', CreateOwner.as_view(), name='create_owner'),
    path('update_owner/<int:pk>', UpdateOwner.as_view(), name='update_owner'),
    path('detail_owner/<int:pk>', DetailOwner.as_view(), name='detail_owner'),
    path('delete_owner/<int:owner_id>', delete_owner, name='delete_owner'),
    path('create_message', MessageCreate.as_view(), name='create_message'),
    path('invite/', InviteView.as_view(), name='invite'),

    path('house_list', HouseList.as_view(), name='house_list'),
    path('create_house', CreateHouse.as_view(), name='create_house'),
    path('update_house/<int:pk>', UpdateHouse.as_view(), name='update_house'),
    path('detail_house/<int:pk>', HouseDetail.as_view(), name='detail_house'),
    path('delete_house/<int:house_id>', delete_house, name='delete_house'),

    path('flat_list', FlatList.as_view(), name='flat_list'),
    path('get_section_level', get_section_level, name='get_section_level'),
    path('create_flat', CreateFlat.as_view(), name='create_flat'),
    path('update_flat/<int:pk>', UpdateFlat.as_view(), name='update_flat'),
    path('detail_flat/<int:pk>', FlatDetail.as_view(), name='detail_flat'),
    path('delete_flat/<int:pk>', delete_flat, name='delete_flat'),

    path('counter_list', CounterView.as_view(), name='counter_list'),
    path('create_counter', CreateCounter.as_view(), name='create_counter'),
    path('flat_counter_list/<int:pk>', FlatCounterList.as_view(), name='flat_counter_list'),
    path('detail_counter/<str:pk>', CounterDetail.as_view(), name='counter_detail'),
    path('update_counter/<str:pk>', UpdateCounter.as_view(), name='update_counter'),
    path('get_section_flat', get_section_flat, name='get_section_flat'),
    path('get_flats', get_flats, name='get_flats'),
    path('get_flats_by_owner', get_flats_by_owner, name='get_flats_by_owner'),
    path('cashbox_list', CashBoxList.as_view(), name='cashbox_list'),
    path('receipt_list', ReceiptList.as_view(), name='receipt_list'),
]